In [1]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference between the data types of list and an array_list.

In [4]:

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [5]:
for elem in list_:
    print(type(elem))
    
for elem in array_list:
    print(type(elem))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

In [6]:
array_list = np.array(object = list_, dtype = int)

Yes, there will be a difference in data type of the elements

In [9]:
for elem in list_:
    print(type(elem))
    
for elem in array_list:
    print(type(elem))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [13]:
#Consider the below code to answer further questions:
    
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

## Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [17]:
print(num_array.shape)
print(num_array.size)

(2, 3)
6


## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [20]:
array = np.zeros((3,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [24]:
array = np.identity(5)
print(array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
